# Generated by Django 2.0 on 2019-04-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_name', models.CharField(max_length=30)),
                ('API_url', models.TextField()),
                ('API_para', models.TextField()),
                ('API_remark', models.TextField()),
                ('API_way', models.IntegerField(choices=[(0, 'POST'), (1, 'GET')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='API_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reslut_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50)),
                ('interface_result', models.TextField()),
                ('interface_remark', models.TextField()),
                ('interface_rel_result', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('API', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_project.API')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_ver', models.CharField(max_length=10)),
                ('project_url', models.TextField()),
                ('project_type', models.IntegerField(choices=[(0, '启用'), (1, '禁用')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('project_remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('userimage_url', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_project.Project'),
        ),
    ]
